
import { Metadata } from "next";
import ProductList from "../components/productList";
import { Product } from "../types/product";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };

export default async function DashboardPage() {
  const res = await fetch("https://fakestoreapi.in/api/products", {
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch products");
  }

  const data = await res.json();
  const products: Product[] = data.products;

  return <ProductList products={products} />;
}
